config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "rides#index"

  resources :users do
    member do
      get :rides
    end
    resources :cars
  end
  resources :rides do
    resources :user_rides do
      member do
        post :accept
        post :reject
      end
    end
    resources :reviews
    member do
      post :finish
    end
  end
  resources :reviews

end

app/models/car.rb
class Car < ActiveRecord::Base
  AVAILABLE_SEATS = [1, 2, 3, 4, 5, 6]

  belongs_to :owner, class_name: 'User'

  validates :brand, presence: true
  validates :model, presence: true
  validates :seats, inclusion: { in: AVAILABLE_SEATS }

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  expose(:cars) { current_user.cars }
  expose(:car)


  def create
    self.car = Car.new(car_params)

    if self.car.save
      current_user.cars << car
      flash[:success] = 'Car successfully added!'
      redirect_to user_cars_path(current_user)
    else
      render action: 'new'
      flash[:error] = "Couldn't create the car!"
    end
  end

  def update
    if self.car.update(car_params)
      flash[:success] = 'Car successfully updated!'
      redirect_to user_cars_path(current_user)
    else
      render action: 'edit'
      flash[:error] = "Couldn't update the car!"
    end
  end

  def destroy
    if self.car.destroy
      flash[:success] = 'Car deleted!'
      redirect_to user_cars_path(current_user)
    else
      render action: 'index'
      flash[:error] = "Couldn't destroy the car!"
    end
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :seats)
  end

end

app/helpers/cars_helper.rb
module CarsHelper

  def car_name(car)
    return '' if car.nil?
    "#{car.brand} #{car.model}"
  end
end

app/views/cars/_form.html.haml
= simple_form_for([current_user, car], html: {class: 'form-horizontal' }) do |f|
  = f.input :brand, label: 'Brand'
  = f.input :model, label: 'Model'
  = f.input :seats, label: 'Number of seats', collection: Car::AVAILABLE_SEATS, default: Car::AVAILABLE_SEATS[0]
  %br
  %p
    = f.button :submit, class: 'btn btn-primary'
    = link_to 'Cancel', :back, class: 'btn btn-default'

app/views/cars/edit.html.haml
.row
  .col-lg-12
    = render partial: 'form'

app/views/cars/index.html.haml
.row
  .col-lg-12
    %table.table
      %thead
        %tr.info
          %td Id
          %td Brand
          %td Model
          %td Seats
          %td
          %td
            -if current_user.cars.empty?
              = link_to "Add new car", new_user_car_path(current_user), class: 'btn btn-primary'
            -else
              %button.btn.btn.primary.disabled Add new car
      %tbody
      - cars.each do |car|
        %tr
          %td= car.id
          %td= car.brand
          %td= car.model
          %td= car.seats
          %td= link_to "Edit", edit_user_car_path(current_user, car), class: 'btn btn-default'
          %td= link_to "Destroy", [current_user, car], method: 'delete', class: 'btn btn-danger'

app/views/cars/new.html.haml
.row
  .col-lg-12
    = simple_form_for(car, url: new_user_car_path(current_user), html: {class: 'form-horizontal' }) do |f|
      = f.input :brand, label: 'Brand'
      = f.input :model, label: 'Model'
      = f.input :seats, label: 'Number of seats', collection: Car.AVAILABLE_SEATS

      %p
        = f.button :submit
        = link_to 'Cancel', :back