config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "rides#index"

  resources :users do
    member do
      get :rides
    end
    resources :cars
  end
  resources :rides do
    resources :user_rides do
      member do
        post :accept
        post :reject
      end
    end
    resources :reviews
    member do
      post :finish
    end
  end
  resources :reviews

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  expose(:attended_rides) { current_user.attended_rides }
  expose(:review)

  def index
  end
  
  def new
  end
  
  def create
    self.review = Review.new(review_params)
    binding.pry
    if self.review.save
      redirect_to reviews_path
    else
      render action: 'new'
    end
  end

  def review_params
    params.require(:review).permit(:reviewer_id, :ride_id, :rating, :comment)
  end
  
  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def reviewed?(ride_id)
    get_review(ride_id)
  end
  
  def get_review(ride_id)
    Review.where(reviewer_id: current_user.id, ride_id: ride_id).first
  end
end

app/views/reviews/_ride.haml
.panel.panel-default
  .panel-heading
    = ride.owner.email
  .panel-body
    .row
      .col-lg-3
        .container
          %h3= "#{ride.owner.firstname} #{ride.owner.lastname}"
          = image_tag(ride.owner.gravatar)
      .col-lg-3
        .span.center-aligned
          %h2= start_point(ride.points).name
          %span.glyphicon.glyphicon-arrow-down
          %h2= end_point(ride.points).name
      .col-lg-6
        %h3= ride.departure_at.strftime("%A, %d %B %Y, %H:%M")
        %p= ride.description    
    .panel-footer
      .row
        .col-lg-6
          .span.left_aligned
        - if reviewed?(ride.id)
          .col-lg-6.col-lg-pull-3
            %h3 Your review
            %h4 Rating
            = get_review(ride.id).rating
            %h4 Comment
            = get_review(ride.id).comment
        - else
          = link_to 'Review!', new_ride_review_path(ride), class: "btn btn-primary"

app/views/reviews/index.haml
.row
  .col-sm-12
    - if attended_rides
      - attended_rides.each do |ride|
        = render partial: 'reviews/ride', locals: { ride: ride, show_link: true }
    - else
      %h You have not attended any ride yet!

app/views/reviews/new.haml
.row
  .col-sm-12.col-md-8.col-md-push-2 
    %h1 Review the Ride!
    = simple_form_for review, html: { class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
      = f.hidden_field :reviewer_id, value: current_user.id
      = f.hidden_field :ride_id, value: params[:ride_id]
      = f.input :rating
      = f.input :comment
      
      = f.submit 'Review', class: 'btn btn-primary pull-right'

    