config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "rides#index"

  resources :users do
    member do
      get :rides
    end
    resources :cars
  end
  resources :rides do
    resources :user_rides do
      member do
        post :accept
        post :reject
      end
    end
    resources :reviews
    member do
      post :finish
    end
  end
  resources :reviews

end

app/models/ride.rb
class Ride < ActiveRecord::Base

  belongs_to :owner, class_name: "User"
  has_many :points
  has_many :user_rides

  accepts_nested_attributes_for :points, :reject_if => :all_blank, :allow_destroy => true

  validates :departure_at, presence: true
  validates :description, presence: true

  def active?
    Time.now < departure_at
  end

  def finish!
    self.finished = true
    self.save
  end

  def owned_by?(user)
    return false if user.nil?
    user.id == owner.id
  end

  def start_point
    points.where(number: 0).first
  end

  def end_point
    points.where(number: points.length - 1).first
  end

  def request_status(user)
    user.user_rides(user_id: user.id).try(:last).try(:status)
  end

  def seats_available
    return 0 unless owner.cars.any?
    owner.car.seats - user_rides.accepted.count
  end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  expose(:requests) { ride.user_rides }
  expose(:rides) { Ride.order("departure_at ASC") } 
  expose(:ride, attributes: :ride_params)
  expose(:starting_point, model: :point)
  expose(:ending_point, model: :point)

  helper CarsHelper

  def create
    points_hash = params[:ride].delete(:points_attributes)
    if ride.save
      Point.save_points(points_hash, Ride.last.id)
      redirect_to root_path
    else
      render action: 'new'
    end
  end
  
  def ride_params
      params.require(:ride).permit(:departure_at, :description, :owner_id, points_attributes: [:id, :name, :latitude, :longitude, :_destroy])
  end

  def finish
    self.ride = Ride.find(params[:id])
    if self.ride.owned_by?(current_user)
      self.ride.finish!
      redirect_to ride_path(ride)
    else
      flash[:error] = "You don't have authorization to finish this ride"
      redirect_to ride_path(ride)
    end
  end
end

app/helpers/rides_helper.rb
module RidesHelper
  def start_point(points)
    points.where(number: 0).first
  end
  
  def end_point(points)
    points.where(number: points.length-1).first
  end
  
  def rating_average(ride_id)
    sum = 0
    Review.where(ride_id: ride_id).each_with_index do |rev|
      sum = sum + rev.rating
    end
    return sum / Review.where(ride_id: ride_id).length unless Review.where(ride_id: ride_id).length == 0
    'No reviews yet'
  end
end

app/views/rides/_point_fields.haml
.nested-fields
  - unless defined?(intermediate)
    %h3 Intermediate point 
  = f.input :name
  = f.input :latitude
  = f.input :longitude
  = link_to_remove_association "Remove intermediate point", f, class: 'btn btn-default pull-right margin-left' unless defined?(intermediate)

app/views/rides/_request.html.haml
.panel.panel-default
  .panel-body
    .row
      .col-sm-12.col-lg-4
        = request.user.firstname
        = request.user.lastname
        = request.user.email
      .col-sm-12.col-lg-4
        Current status:
        - if request.status == 'rejected'
          %span.text-uppercase.btn.btn-danger= request.status
        - elsif request.status == 'accepted'
          %span.text-uppercase.btn.btn-success= request.status
        - else 
          %span.text-uppercase.btn.btn-warning= request.status
      .col-sm-12.col-lg-4
        .pull-right
          - unless request.status == 'accepted'
            = link_to 'Approve', accept_ride_user_ride_path(request.ride, request), method: :post, class: 'btn btn-success'
          - unless request.status == 'rejected'
            = link_to 'Reject', reject_ride_user_ride_path(request.ride, request) , method: :post, class: 'btn btn-danger'

app/views/rides/_requests_list.html.haml
- if current_user == ride.owner
  %h3 Requests for this ride
  - if requests.first != nil
    - requests.each do |request|
      = render partial: 'rides/request', locals: { request: request }
  - else
    %p Nobody requested for this ride yet. 
- elsif ride.user_rides.alreadyrequested?(current_user, ride)
  %h3 Your request for this ride:
  Status:
  %span.text-uppercase.btn.btn-primary= ride.request_status(current_user)
  

app/views/rides/_ride.haml
.panel.panel-default
  .panel-heading
    = ride.owner.email
    - if show_link
      = link_to 'Show this ride', ride_path(ride), class: "pull-right"
  .panel-body
    .row
      .col-lg-3
        .container
          %h3= "#{ride.owner.firstname} #{ride.owner.lastname}"
          = image_tag(ride.owner.gravatar)
      .col-lg-3
        .span.center-aligned
          %h2= ride.start_point.name
          %span.glyphicon.glyphicon-arrow-down
          %h2= ride.end_point.name
      .col-lg-6
        %h3= ride.departure_at.strftime("%A, %d %B %Y, %H:%M")
        %p= ride.description
        - unless current_user == ride.owner
          - if UserRide.alreadyrequested?(current_user, ride)
            .alert.alert-info You requested a place for this ride.
          - else
            = link_to 'I want to ride!', ride_user_rides_path(ride), method: :post, class: "btn btn-primary"
        - else
          = link_to 'This is your ride!', ride_path(ride), class: 'btn btn-warning'
  .panel-footer
    .row
      .col-lg-6
        .span.left_aligned
          %h4 Car:
      .col-lg-3
        .span.left_aligned
          %h4 Available seats:
      .col-lg-3
        - if ride.owned_by?(current_user)
          - unless ride.finished?
            = link_to "Finish ride", finish_ride_path(ride), method: :post, class: "btn btn-primary"
          - else
            %button.btn.btn.primary.disabled Ride finished
    .row
      .col-lg-6
        .span.left_aligned
          = car_name(ride.owner.car)
      .col-lg-3
        .span.left_aligned
          = ride.seats_available
      .col-lg-3
    - if ride.finished?
      .row
        .col-lg-6
          %h4 Rating Average:
          = rating_average(ride.id)

app/views/rides/index.html.haml
.row
  .col-sm-12
    - rides.each do |ride|
      - if ride.active?
        = render partial: 'rides/ride', locals: { ride: ride, show_link: true }

app/views/rides/new.haml
.row
  .col-sm-12.col-md-8.col-md-push-2 
    = simple_form_for ride, html: { class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|
      = f.hidden_field :owner_id, value: current_user.id
      %h3 Route
      = f.input :departure_at, :as => :datetime_picker
      = f.input :description
      #points
        %h3 Starting Point
        = f.simple_fields_for :points, starting_point do |point|
          = render partial: 'point_fields', locals: { f: point, intermediate: false }
        .links
          = link_to_add_association 'Add intermediate point', f, :points, class: 'btn btn-default pull-right'
        %h3 Ending Point
        = f.simple_fields_for :points, ending_point do |point|
          = render partial: 'point_fields', locals: { f: point, intermediate: false }

      = f.submit 'Create', class: 'btn btn-primary pull-right'

app/views/rides/show.html.haml
= render partial: 'rides/ride', locals: { ride: ride, show_link: false }
.row
  .col-sm-12
    = render partial: 'rides/requests_list'