config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "rides#index"

  resources :users do
    member do
      get :rides
    end
    resources :cars
  end
  resources :rides do
    resources :user_rides do
      member do
        post :accept
        post :reject
      end
    end
    resources :reviews
    member do
      post :finish
    end
  end
  resources :reviews

end

app/views/layouts/_flashes.html.haml
- flash.each do |type, message|
  %div{ class: "alert #{ bootstrap_class_for(type) } fade in" }
    %button{ class: 'close', 'data-dismiss' => 'alert' } ×
    = message

app/views/layouts/_login_box.html.haml
%ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
        = user_signed_in? ? "Hello,  #{ current_user.firstname }" : 'Menu'
        %span.caret
      %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", role: "menu"}
        - if user_signed_in?
          %li{role: "presentation"}
            = link_to "Account", edit_user_registration_path, { role: 'menuitem', tabindex: '-1' }
          - if current_user.cars?
            %li{:role => "presentation"}
              = link_to 'Create Ride', new_ride_path, { role: 'menuitem' }
          %li{:role => "presentation"}
            = link_to 'My Rides', rides_user_path(current_user), { role: 'menuitem' }
          %li{:role => "presentation"}
            = link_to 'Reviews', reviews_path, { role: 'menuitem' }
          %li{:role => "presentation"}
            = link_to 'Cars', user_cars_path(current_user), { role: 'menuitem' }
          %li{role: "presentation"}
            = link_to 'Logout', destroy_user_session_path, method: :delete, role: "menuitem", tabindex: "-1"
  - else 
    %li{role: "presentation"}
      %a{href: new_user_session_path, role: "menuitem", tabindex: "-1"} Get-in

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{ role: 'navigation' }
  .navbar-header
    %button.navbar-toggle{ data: { target: '.navbar-ex1-collapse', toggle: 'collapse' }, type: 'button' }
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to 'Bulbacar', root_url, class: 'navbar-brand'
  .collapse.navbar-collapse.navbar-ex1-collapse.navbar-right
    = render partial: 'layouts/login_box'

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %title Bulbacar
  %body
    = render partial: 'layouts/navbar'
    .container
      = render partial: 'layouts/flashes'
      = yield